name: imagecaptioning
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.6
  flutter_screenutil: ^5.0.0+2
  pull_to_refresh: ^2.0.0
  flutter_svg: ^0.23.0+1
  backdrop: ^0.7.1
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  shared_preferences: ^2.0.9
  flutter_bloc: ^8.0.1
  retrofit: ^2.0.1
  get_it: ^7.2.0
  injectable: ^1.4.1
  signalr_core: ^1.1.1
  equatable: ^2.0.3
  bloc_concurrency: ^0.2.0
  image_picker: ^0.8.4+4
  stream_transform: ^2.0.0
  material_floating_search_bar: ^0.3.7
  flutter_image_compress: ^1.1.0
  image: ^3.1.1
  image_cropper: ^1.4.1
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.0.6
  retrofit_generator: ^2.0.1

flutter_native_splash:
  image: assets/images/ISMAIA.png
  android_gravity: fill
  color: '#f9f9f9'

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
          weight: 400
